# Generated by Django 3.2.2 on 2021-05-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpAddress',
        ),
    ]
