# Generated by Django 3.2.2 on 2021-05-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ipaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='title',
            new_name='ip',
        ),
    ]
